version: '3.9'

services:
  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
      - /app/.venv
    command: >
      sh -c "/app/.venv/bin/python manage.py migrate && /app/.venv/bin/python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend/src:/app/src
    depends_on:
      - backend

  swagger-ui:
    image: swaggerapi/swagger-ui:latest
    ports:
      - "8081:8080"
    volumes:
      - ../swagger:/swagger:ro   
    environment:
      SWAGGER_JSON: /swagger/swagger.yaml
